- client/eslint.config.mjs
- client/package-lock.json
- client/package.json
- server/eslint.config.mjs
- server/package-lock.json
- server/package.json
server 
function ต้องตั้งชื่อแบบ camelCase เลยขึ้นแจ้งเตือนดังนี้ 
file name ต้องตั้งชื่อแบบ kabab-case
client
function ต้องตั้งชื่อแบบ PascalCase  
*** หมายเหตุ ที่ในรูปเขียนว่าจะต้องเป็น formats : PascalCase , camelCase ที่เพิ่ม camelCase มาเนื่องจากบางฟังก์ชันของ framework บางตัวที่ import มาเขาใช้ camelCase เลยต้องใส่ไว้ แต่ให้รู้โดยทั่วกันว่าการเขียนฟังก์ชันจะใช้ PascalCase 
file name ต้องตั้งชื่อแบบ kabab-case
> <👷 build>[server,client]:{eslint}

- client/app/globals.css
- client/components/ui/dropdown-menu.tsx
- client/package-lock.json
- client/package.json
add dropdown components from shadcn and modify outline of DropdownMenuTrigger
> <👷 build>[client,components]:{install dropdown-menu component from shadcn}

- docker-compose.yml
- server/.env.server
- server/prisma/schema.prisma
ตั้งชื่อดาต้าเบสใหม่ ของ docker 
ตั้งชื่อให้เป็นตัวเล็ก
> <🐛 fix>[(server, client), server: prisma]:{change name database docker , Set the model name to lowercase in another database. }

- client/components/textfield.tsx
> <✨ add>[client:component]:{create textfield component}

- server/Controllers/patrol-controller.ts
- server/Controllers/preset-controller.ts
- server/Routes/patrol-route.ts
- server/index.ts
> <✨add>[server: Controllers, server: Routes]:{getPatrol, getAllPatrols}

- server/Controllers/patrol-controller.ts
- server/Routes/patrol-route.ts
- server/prisma/schema.prisma
> <✨add>[server: Controllers, server: Routes]:{createPatrols}

- client/components/ui/badge.tsx
> <💄 style>[client:component]:{update profile-dropdown color}

- server/Controllers/user-controller.ts
- server/Routes/user-route.ts
getAllUsers
getUser
createUsers
> <✨add>[server: Controllers: user-controller, server: Routes: user-route]:{getUser, getAllUsers, createUsers}

- server/Controllers/patrol-controller.ts
- server/Routes/patrol-route.ts
- server/prisma/schema.prisma
> <⚡️ perf>[server]:{Add role based access control for patrol and checklist visibility ADMIN, INSPECTOR}

- server/prisma/schema.prisma
เปลี่ยนแปลงรายละเอียดของชื่อฟิลด์แต่ละตาราง ตัวแรกจะเป็นชื่อแบบปกติ เช่น id ก็จะเป็น id เลย แต่ปรับแก้คือ ใส่ชื่อของตารางเข้าไปก่อนหน้า อย่างเช่นตาราง Checklist ก็จะเขียนเป็น cl_id และปรับแก้ให้เป็นแบบ snake_case ทั้งหมด ตอนแรกยังมี camelCase ในบางตาราง 
และลบ model user_has_patrol ทิ้งไป
> <♻️ refactor>[server]:{update schema table}

- server/Controllers/patrol-controller.ts
- server/Controllers/user-controller.ts
- server/jest.config.js
- server/package-lock.json
- server/package.json
- server/tests/defect.test.ts
- server/tests/patrol.test.ts
- server/tests/preset.test.ts
- server/tests/user.test.ts
- server/tests/util.test.ts
- server/tsconfig.json
จัดทำ unit test ทุกฟังก์ชันใน controller โดยใช้ jest เป็น testing framework
> <✅ test>[server: tests]:{make unit test all function in controller}

- server/Controllers/user-controller.ts
- server/Utils/type.ts
ทำการแก้ไข function ต่าง ๆ ภายใน user-controller เนื่องจากมีการเปลี่ยนแปลงของ interface ของ user ตอนแรก profile เป็น array ซึ่งมันไม่เคยเป็นแบบนั้น user 1 คน ควรมี 1 profile 
getAllUsers
getProfile
> <🐛 fix>[server: Controller]:{Fix function in user-controller}

- client/app/[locale]/patrol/page.tsx
- client/app/type.ts
- client/components/badge-custom.tsx
- client/components/defect.tsx
> <✨add>[client:component]{create defect component}

- client/components/checklist-dropdown.tsx
- client/components/user-dropdown.tsx
- client/package-lock.json
- server/Controllers/user-controller.ts
> <🐛 fix>[server: Controller]:{Fix function in user-controller query profile from array to object type}  

- client/app/type.ts
- client/components/patrol-card.tsx
- client/middleware.ts
- server/Controllers/defect-controller.ts
- server/Controllers/patrol-controller.ts
- server/Controllers/preset-controller.ts
- server/Controllers/user-controller.ts
- server/Utils/type.ts
- server/prisma/schema.prisma
> <♻️ refactor>[server, client]:{fix profile  from array to single object}

- client/components/header.tsx
- client/components/notification.tsx
- client/components/ui/card.tsx
> <✨add>[client:component]{add notification component}

- client/app/[locale]/patrol/page.tsx
- client/components/checklist-dropdown.tsx
- client/components/date-picker.tsx
- client/components/patrol-card.tsx
- client/components/user-dropdown.tsx
- client/messages/en.json
- client/messages/th.json
> <✨add>[client:component]{add thai and english translation for  create patrol card and patrol card it self}

- client/app/layout.tsx
> <🐛 fix>[server:Routes,server:Controllers]:{add index file in empty folder}

- client/app/layout.tsx
- server/Controllers/patrol-controller.ts
- server/Routes/patrol-route.ts
- server/prisma/schema.prisma
> <✨add>[server:controller]{add new finish patrol function}

- client/lib/utils.ts
> <✨add>[client:utils]{add export to excel function}

- client/app/[locale]/patrol/page.tsx
- client/app/type.ts
- client/components/patrol-card.tsx
- client/components/profile-dropdown.tsx
- client/components/user-dropdown.tsx
- server/Controllers/patrol-controller.ts
- server/Routes/patrol-route.ts
> <✨add>[server:controller]{add new remove patrol function}&&<✨add>[client:component]{make user-dropdown and patrol-card show correct user image}

- server/Controllers/defect-controller.ts
- server/Routes/defect-route.ts
> <✨add>[server:controller & route]{createDefect, updateDefect, getDefect, getAllDefect, deleteDefect} 

- server/Controllers/defect-controller.ts
- server/Controllers/patrol-controller.ts
- server/Routes/defect-route.ts
- server/Routes/patrol-route.ts
> <🐛 fix>[server: Controller & route]: {format response fields for defect and Comment}

- client/app/[locale]/patrol/[id]/page.tsx
- client/components/patrol-card.tsx
> <🐛 fix>[client:patrol-card]:{fix translate issue}

- server/Controllers/defect-controller.ts
- server/Controllers/patrol-controller.ts
- server/Controllers/user-controller.ts
- server/Routes/patrol-route.ts
- server/Routes/user-route.ts
> <✨add>[server:controller & route]{updateUser, deleteUser}: refactor variable names to 'result' in defectController and patrolController

- .vscode/settings.json
- client/app/[locale]/patrol/page.tsx
- client/app/type.ts
- client/components/date-picker.tsx
- client/components/filter-date.tsx
- client/lib/utils.ts
สามารถ sort รายการตรวจ Patrol จาก หมายเลขเอกสาร (Doc no.) และ วันที่ (Date) และสามารถเรียงจากมากไปน้อย หรือน้อยไปมากได้
สามารถ filter รายการตรวจ Patrol จาก ช่วงของวันที่ (DatePickerWithRange), สถานะ (Status) และ รูปแบบการตรวจ (Preset) ได้  
และหากทำการรีเฟรชหน้าเว็บ filter ก็ยังคงมีอยู่ โดยใช้ localStorage ในการเก็บค่า filter
> <✨add>[client: patrol-list-view]{create function sort and filter}

- client/app/[locale]/patrol/page.tsx
สามารถทำการ search รายการตรวจ Patrol ได้จากทั้ง วันที่ตรวจ , หมายเลขใบ patrol , ชื่อ preset , สถานะของใบ patrolและ ชื่อของผู้ตรวจ patrol
> <✨add>[client: patrol-list-view]:{create function search}

- client/package.json
- server/.env copy
- server/Controllers/patrol-controller.ts
- server/Controllers/user-controller.ts
- server/Routes/patrol-route.ts
- server/Utils/cors.ts
- server/Utils/socket.ts
- server/index.ts
- server/package.json
> <👷 build>[client, server]{install socket real-time data into client and server}

- client/app/[locale]/patrol/page.tsx
- client/app/layout.tsx
- client/app/type.ts
- client/components/badge-custom.tsx
- client/components/notification.tsx
- client/components/socket-indicator.tsx
- client/components/socket-provider.tsx
- client/lib/utils.ts
- client/messages/en.json
- client/messages/th.json
- server/Controllers/patrol-controller.ts
- server/Controllers/util-controller.ts
- server/Routes/util-route.ts
- server/Utils/socket.ts
- server/package.json
- server/prisma/migrations/init/migration.sql
- server/prisma/schema.prisma
> <✨add>[client:component, server:controller]{add notification system}

- client/app/[locale]/patrol/[id]/page.tsx
- client/components/badge-custom.tsx
- client/components/defect.tsx
- client/next.config.mjs
- server/Controllers/defect-controller.ts
- server/Controllers/patrol-controller.ts
- server/Controllers/user-controller.ts
- server/prisma/data/images.ts
- server/prisma/migrations/20241016185623_init/migration.sql
- server/prisma/schema.prisma
จัดทำให้ผู้ตรวจสามารถดูผลของการ Report Defect ได้ และมีการแก้ไข patrol-controller เพื่อให้ส่งข้อมูลที่ถูกต้องออกมาให้ component ใช้ และ defect-controller แก้ให้ ชื่อของไฟล์รูปในเครื่องและฐานข้อมูลชื่อเหมือนกัน
และมีการแก้ไข schema รายละเอียดอ่านใน commit 
https://github.com/user-attachments/assets/7353491b-99a1-4cca-ab2f-bdf46b520c69
> <✨add>[client:patrol-view-defect]{show ReportDefect Component on page}

- client/app/[locale]/patrol/[id]/page.tsx
- client/components/patrol-card.tsx
> <♻️ refactor>[client:patrol-checklist]:{make user see only they assign checklist}

- server/src/Controllers/util-controller.ts
แก้ไขให้ Remember Me ตอน Login ใช้งานได้
ตอนที่ไม่ได้กด Remember Me authToken มีอายุ 1 ชั่วโมง 
ตอนกด Remember Me authToken มีอายุ 30 วัน
> <🐛 fix>[server:util-controller]:{fix remember me login}

- client/components/notification.tsx
- server/src/Controllers/util-controller.ts
> <🐛 fix>[client: notification, server: Controllers]:{fix notification real time}

- server/src/Controllers/preset-controller.ts
- server/src/Routes/preset-route.ts
https://github.com/user-attachments/assets/3ce17c99-ec5b-47d1-a6a8-5593e7d67295
> <✨add>[server: Controllers]{add create and update controller for preset}

- server/src/Controllers/defect-controller.ts
- server/src/Controllers/location-controller.ts
- server/src/Controllers/patrol-controller.ts
- server/src/Controllers/preset-controller.ts
- server/src/Controllers/user-controller.ts
- server/src/Controllers/util-controller.ts
- server/src/Routes/preset-route.ts
- server/src/Routes/user-route.ts
เพิ่ม function getChecklist และ getAllChecklist  และ Comment Code
> <✨add>[server:Controller]:{add new controllerfor getChecklist, getAllChecklist  and fix removeUser api}

- server/tests/util.test.ts
เขียน unit test สำหรับฟังก์ชันใน util-controller
> <✨add>[server: tests]{create unit test function in util-controller}

- server/src/Controllers/preset-controller.ts
- server/src/Routes/preset-route.ts
> <✨add>[server:Controller]:{add new controller getChecklist api}

- server/src/Controllers/preset-controller.ts
- server/src/Routes/preset-route.ts
ทำการเขียนฟังก์ชัน removeChecklsit แต่ไม่ใช่การลบ checklist จริง ๆ ออกไป แต่เปลี่ยนค่าของ latest ให้เป็น false ซึ่งหมายถึงไม่ใช้งานแล้ว
Before:
After:
> <✨add>[server: Controller]:{create function removeChecklist}

- client/app/[locale]/defect/[id]/page.tsx
- client/app/[locale]/supervisor/layout.tsx
- client/app/[locale]/supervisor/page.tsx
- client/app/type.ts
- client/components/alert-custom.tsx
- server/src/Controllers/defect-controller.ts
https://github.com/user-attachments/assets/dc7ef950-c67f-4d16-9ec2-1cf9e18dc0e8
> <✨add>[client: defect]:{add defect view page}

- client/app/layout.tsx
- client/components/ui/toast.tsx
- client/components/ui/toaster.tsx
- client/package-lock.json
- client/package.json
error
default
success
ตัวอย่างการใช้
const fakeFunction = async () => {
try {
toast({
variant: "success",
title: "Uh oh! Something went wrong.",
description: "There was a problem with your request.",
})
} catch (error) {
console.error("Failed", error);
}
};
> <💄 style>[client: components]:{fix AlertBox component}

- client/app/[locale]/patrol/page.tsx
- client/components/patrol-card.tsx
- client/components/profile-dropdown.tsx
- client/messages/en.json
- server/src/Controllers/patrol-controller.ts
แก้ไขให้ update หน้าเว็บโดยรับ response หลังจาก createDefect และนำมาต่อท้ายข้อมูล state เดิม
https://github.com/user-attachments/assets/f5b4e362-5696-49de-b18f-700e53d25abd
แก้ PatrolCard ถ้าเป็นภาษาไทยจะเป็น พุทธศักราช อังกฤษ คริสต์ศักราช
> <⚡️ perf>[client: patrol-list, server: Controller]:{update state after createPatrol}

- client/components/patrol-card.tsx
- client/lib/utils.ts
แก้เลข Patrol Id ให้ขึ้นต้นด้วย P ตามด้วยเลข ID 4 หลัก และลบ function ที่ซ้ำซ้อน
> <💄 style>[client: components]:{format patrol id}

- client/components/patrol-checklist.tsx
- server/src/Routes/defect-route.ts
- server/src/Routes/user-route.ts
แก้ Routes ให้ใช้ Function authorzied หลังจากเรียก Function authenticateUser
> <🐛fix>[server: Routes:]:{fix route use authorzied function before authenticateUser}

- client/app/type.ts
- client/components/badge-custom.tsx
- client/components/defect.tsx
- client/lib/utils.ts
- server/src/Controllers/defect-controller.ts
แก้ไข UI หน้า Defect View และ แปลภาษา TH/EN
ทำ API getAllDefect เพิ่มฟังก์ชันในการ Search และ Filter
> <✨add>[client: defect-view, server: Controllers]:{Edit the Component and do a search}

- client/app/[locale]/admin/user/page.tsx
- client/components/admin-sidebar.tsx
- client/components/alert-custom.tsx
- client/package.json
- server/src/Controllers/user-controller.ts
https://github.com/user-attachments/assets/2fe739ac-545f-483e-8787-3e1a3957e11b
> <✨add>[client: user]:{add user management module to system}

- client/app/[locale]/defect/[id]/page.tsx
- client/app/[locale]/patrol-defect/layout.tsx
- client/app/[locale]/patrol-defect/loading.tsx
- client/app/[locale]/patrol-defect/page.tsx
- client/app/[locale]/patrol/[id]/page.tsx
- client/components/alert-defect.tsx
- client/components/badge-custom.tsx
- client/components/header.tsx
- client/components/patrol-checklist.tsx
- client/components/report-defect.tsx
- client/components/ui/progress.tsx
- server/src/Controllers/defect-controller.ts
- server/src/Controllers/patrol-controller.ts
- server/src/Routes/patrol-route.ts
สร้างหน้า patrol-defect และแก้ไข Report Defect Component ให้เหมือนกับ figma รวมถึง แก้ไข controller ที่เกี่ยวข้องอื่น ๆ และยังมีการสร้าง alert defect component สำหรับเมื่อกดปุ่ม report หรือ edit แล้วแสดง alert ขึ้นมา โดยที่ทำมาทั้งหมดสามารถรับชมได้จากวิดีโอต่อไปนี้
Report Defect ส่งค่าอย่าง Realtime โดยไม่ต้อง refresh หน้าจอ
https://github.com/user-attachments/assets/8d6855eb-d831-40c5-93c1-3076efb9eea0
Edit Defect ส่งค่าอย่าง Realtime โดยไม่ต้อง refresh หน้าจอ
https://github.com/user-attachments/assets/3285e29f-c7e5-4bb9-b1dc-ddff440962ec
หน้า patrol-defect ที่ component Report Defect แสดงไม่เหมือนกับ หน้า patrol-view ตรงที่มี ปุ่ม navigate ที่สามารถไปยังใบ Patrol ได้
https://github.com/user-attachments/assets/9b9f2020-c776-4592-a625-43e9b62aa1a5
> <✨add>[client: patrol-defect]{add patrol-defect page} 

- client/app/[locale]/defect/page.tsx
- client/app/type.ts
- client/components/defect.tsx
- client/lib/utils.ts
- client/messages/en.json
- client/messages/th.json
- server/src/Controllers/defect-controller.ts
ฟังกชัน Soft และ Filter ของหน้า Defect list
> <✨add>[client: defect-list]{create function sort and filter search}

- server/prisma/migrations/20241224150641_update/migration.sql
- server/prisma/schema.prisma
ลบความสัมพันธ์หลายต่อหลายระหว่าง user และ checklist
> <♻️refactor>:[server:prisma]:{remove _user table is never used}

- client/app/[locale]/admin/settings/layout.tsx
- client/app/[locale]/admin/settings/location-&-zone/page.tsx
- client/app/[locale]/admin/settings/patrol-checklist/page.tsx
- client/app/[locale]/admin/settings/patrol-preset/[id]/loading.tsx
- client/app/[locale]/admin/settings/patrol-preset/[id]/page.tsx
- client/app/[locale]/admin/settings/patrol-preset/create/loading.tsx
- client/app/[locale]/admin/settings/patrol-preset/create/page.tsx
- client/app/type.ts
- server/src/Controllers/preset-controller.ts
จัดทำหน้า patrol preset view โดยมีทั้งหน้าที่ Create Preset และ Edit Preset 
โดยได้มีการปรับแต่ง หลังบ้านในส่วนของฟังก์ชัน createPreset และ updatePreset ใน preset-controller 
ดูได้จากวิดีโอข้างต้น 
Create Preset 
https://github.com/user-attachments/assets/0e10a60c-ba03-4a00-a0e1-b887b81a5646
Edit Preset
https://github.com/user-attachments/assets/922fb2e6-6523-45e6-94c3-1bfa1e2a70e7
> <✨add>[client: patrol-preset-view]:{add patrol-preset-view page} 

- client/app/[locale]/comment/page.tsx
- client/components/alert-custom.tsx
- client/messages/en.json
- client/messages/th.json
แก้ไข Confirm Box ให้ใช้ Component AlertCustom ,เพิ่ม AlertBox ,และเพิ่มแปลภาษา
> <✨add>[client: comment-list]:{add alertbox and use alertCustom Component}

- .dockerfile
- .dockerignore
- Jenkinsfile
- client/app/[locale]/admin/settings/checklistview/[id]/page.tsx
- client/test.tsx
- docker-compose.jenkins.yml
- docker-compose.yml
- entrypoint.sh
- jenkins.dockerfile
- server/package-lock.json
- server/package.json
- server/prisma/schema.prisma
- server/src/Controllers/location-controller.ts
จัดทำ Jenkins ในการ test และ deploy อัตโนมัติ
> <✨add>[Jenkinfile]:{add jenkins file and docker}

- client/app/[locale]/admin/employees/page.tsx
- client/app/[locale]/admin/settings/location-&-zone/page.tsx
- client/app/[locale]/admin/settings/patrol-checklist/page.tsx
- client/app/[locale]/admin/settings/patrol-preset/[id]/page.tsx
- client/app/[locale]/admin/settings/patrol-preset/create/page.tsx
- client/app/[locale]/comment/page.tsx
- client/app/[locale]/defect/[id]/page.tsx
- client/app/[locale]/profile/page.tsx
- client/components/checklist-dropdown.tsx
- client/components/defect.tsx
- client/components/patrol-card.tsx
- client/components/patrol-checklist.tsx
- client/components/profile-dropdown.tsx
- client/components/report-defect.tsx
- client/components/ui/avatar.tsx
- client/components/ui/hover-card.tsx
- client/components/ui/input.tsx
- client/components/ui/select.tsx
- client/components/ui/textarea.tsx
- client/components/user-dropdown.tsx
- client/messages/en.json
- client/messages/th.json
- server/src/Controllers/preset-controller.ts
- server/src/Controllers/user-controller.ts
เพิ่ม AlertBox กรณีที่ไม่มีอะไรเปลี่ยนแปลง
เพิ่ม เงื่อนไขสำหรับ  Form ใหม่ให้รัดกุมมากขึ้น
แก้ไขสี AvatarFallback ให้ random จาก user.id ทำให้ไม่เกิดการ Random ทุกรอบ
> <🐛 fix>[client: profile]:{fix function update user}

- client/app/[locale]/patrol-defect/page.tsx
- client/app/[locale]/patrol/[id]/detail/page.tsx
- client/app/[locale]/patrol/page.tsx
- client/app/[locale]/profile/page.tsx
- client/components/alert-defect.tsx
- server/src/Controllers/patrol-controller.ts
แก้ไขให้ AlertDefect Component เมื่อเป็นการ edit และ resolve ให้ปิดหน้าต่างไปหลังจากกด Save และแก้ไขให้ปุ่ม Back หน้า profile ใช้งานได้
> <🐛 fix>[client: component]:{fix alert defect} 

- server/package-lock.json
- server/package.json
- server/src/Controllers/location-controller.ts
- server/src/Routes/defect-route.ts
- server/src/Routes/location-route.ts
- server/src/Routes/patrol-route.ts
- server/src/Routes/preset-route.ts
- server/src/Routes/user-route.ts
- server/src/Routes/util-route.ts
- server/src/index.ts
เพิ่ม swagger และจัดทำ API document ทุกเส้น
> <📝docs>[server: Routes]:{add all api document}

- client/app/[locale]/patrol/page.tsx
- client/components/date-picker.tsx
- server/src/Controllers/preset-controller.ts
แก้ Bug Preset แสดง Zone ไม่ถูกต้องและแก้ไขสีปุ่มให้ตรงตาม Figma
> <🐛 fix>:[client: patrol-view]:{fix preset zone bug}

- client/lib/utils.ts
- server/src/Controllers/patrol-controller.ts
> <📝docs>[client:lib:utils]:{make excel tables to has colors and fix tables font size}

- client/app/[locale]/profile/page.tsx
> <♻️refactor>:[client: profile]:{Adjust default value from value = to be default value = instead}

- client/app/[locale]/defect/[id]/page.tsx
- client/app/[locale]/patrol/page.tsx
- client/components/alert-custom.tsx
- client/components/alert-defect.tsx
- client/components/report-defect.tsx
- client/components/ui/alert-dialog.tsx
> <💄 style>[client: defect-view]:{fix responsive ipad pro}

- client/app/[locale]/profile/page.tsx
> <♻️refactor>:[client: profile]:{adjust logic of how to check password change}

- client/app/[locale]/patrol-defect/page.tsx
- client/app/[locale]/profile/page.tsx
- client/messages/en.json
- client/messages/th.json
- server/src/Controllers/user-controller.ts
แก้ไขหน้า Password ให้เช็คจากกรอกให้ครบทุกช่องก่อน จากนั้นเช็ค New กับ Confirm และเช็ค New กับ Current
แก้ไขหน้า Profile ให้เช็คช่องว่างทุกช่อง และแก้ไขบักของ อายุ
> <🐛 fix>[client: profile]:{fix update password handle error and toast}

- client/app/[locale]/admin/settings/patrol-preset/page.tsx
- server/src/Controllers/preset-controller.ts
> <♻️refactor>:[client: admin]:{refactor search logic}

- client/app/[locale]/admin/dashboard/heat-map/[id]/page.tsx
- client/app/[locale]/admin/dashboard/heat-map/page.tsx
- client/app/[locale]/admin/settings/patrol-checklist/[id]/page.tsx
- client/app/[locale]/admin/settings/patrol-checklist/create/page.tsx
- client/app/[locale]/admin/settings/patrol-checklist/page.tsx
- client/app/[locale]/admin/settings/patrol-preset/page.tsx
- client/app/globals.css
- client/components/admin-sidebar.tsx
- client/components/header.tsx
- client/components/ui/avatar.tsx
- client/components/ui/sidebar.tsx
- client/components/ui/toggle.tsx
- client/constants/zone-criteria.ts
- client/messages/en.json
- client/messages/th.json
- client/tailwind.config.ts
แก้ไขให้ Scroll Area เต็มหน้าจอ และแก้ไข สี HeatMap และ Theme Color ให้เหมาะสมและเข้ากับระบบมากขึ้น
> <💄 style>[client: heat-map]:{change theme color and fix scroll area}

- client/app/[locale]/patrol/[id]/detail/page.tsx
- client/components/notification.tsx
- server/src/Controllers/patrol-controller.ts
แก้ไข Notification ให้ Update ข้อมูลถูกต้อง
> <🐛 fix>[client: notification]{fix notification real time fetch}

- client/app/[locale]/admin/settings/patrol-checklist/[id]/page.tsx
- client/app/[locale]/admin/settings/patrol-checklist/create/page.tsx
- client/app/[locale]/admin/settings/patrol-checklist/page.tsx
- client/app/[locale]/admin/settings/patrol-preset/[id]/page.tsx
- client/app/[locale]/admin/settings/patrol-preset/create/page.tsx
- client/app/[locale]/admin/settings/patrol-preset/page.tsx
- client/components/map.tsx
- client/components/ui/table.tsx
> <♻️refactor>:[client: admin]:{Refactor visual and Fix responsive and default value of filter on admin patrol checklist and preset }

- client/app/[locale]/admin/employees/page.tsx
- client/app/[locale]/admin/settings/patrol-checklist/[id]/page.tsx
- client/app/[locale]/admin/settings/patrol-checklist/create/page.tsx
- client/app/[locale]/admin/settings/patrol-checklist/page.tsx
- client/app/[locale]/admin/settings/patrol-preset/[id]/page.tsx
- client/app/[locale]/admin/settings/patrol-preset/create/page.tsx
- client/app/[locale]/admin/settings/patrol-preset/page.tsx
- client/components/map.tsx
- client/components/ui/table.tsx
1.[client:patrol-preset:create:page && client:patrol-preset:[id]]:{change Width title w-1/3 => w-72}
2.[client:[locale]:admin:employees]:{hidetext on Role && Status when screen < 911}
3.[client:[local]:admin:employees]:{change width layout in add new employees}
[Merge Style มารวมแล้ว แก้ Config แล้ว]
> <💄 style>[client:patrol-preset && client:admin:employees]:{change layout}

- client/app/[locale]/patrol/[id]/detail/page.tsx
- client/app/type.ts
- client/components/alert-defect.tsx
- client/components/patrol-checklist.tsx
- client/context/patrol-context.tsx
- client/messages/en.json
- client/messages/th.json
- server/src/Controllers/dashboard-controller.ts
- server/src/Controllers/defect-controller.ts
- server/src/Controllers/patrol-controller.ts
- server/src/Controllers/user-controller.ts
- server/src/Controllers/util-controller.ts
- server/src/Routes/dashboard-route.ts
- server/src/Routes/defect-route.ts
- server/src/Routes/location-route.ts
- server/src/Routes/patrol-route.ts
- server/src/Routes/preset-route.ts
- server/src/Routes/user-route.ts
- server/src/tests/util.test.ts
เพิ่่ม error handle สำหรับตรวจสอบชนิดไฟล์
จัดการโครงสร้าง Folder uploads ใหม่และเก็บรูปผลการแก้ไขปัญหาอันเก่าไว้ตลอด ยกเว้นครั้งที่แก้ไขล่าสุด
แก้ไขปัญหาแจ้งปัญหาเมื่อเข้ามาและมีผลการตรสจจาก localestorage ให้สามารถแจ้งปัญหาได้
> <✨add>[client: alert-defect]:{add handle error file type}

- client/app/[locale]/admin/dashboard/overview/[id]/page.tsx
- client/app/[locale]/admin/settings/patrol-preset/create/page.tsx
- server/src/Controllers/patrol-controller.ts
- server/src/tests/patrol.test.ts
- server/src/tests/util.test.ts
> <🐛fix>[client: overview detail]:{fix wrong path 404 not found}

- client/lib/utils.ts
เพิ่ม Column Annotation ไว้สำหรับแสดงหมายเหตุเมื่อมีการแจ้ง Comments หรือ Defects โดยจะแสดงรายการตารางย่อยโดยประกอบไปด้วยข้อมูล DateTime และ Detail ที่จะแสดงเป็น Rows ตามจำนวน Comments หรือ Defects ที่มีการแจ้งใน Items นั้น ๆ และหากไม่มีการแจ้งจะใส่ข้อมูล "-" ในตาราง
และมีการแก้ไขตาราง Summary โดยลบในส่วนของการตรวจจับ Failed ออกไป
> <🐛fix>[client:lib:utils]:{add Annotation table in Patrol Tables to make it show dateTime and Detail when has comments or defects}

- client/app/[locale]/patrol/[id]/detail/page.tsx
- client/app/[locale]/patrol/[id]/report/page.tsx
แก้ไขบั้กปุ่ม Export Patrol หายไป
> <🐛fix>[client: patrol-view]:{fix export patrol}

- client/components/patrol-checklist.tsx
แก้ไข bug ตอน create comment ให้ update state และส่ง socket อย่างถูกต้องและแก้ไขให้ build ได้
https://github.com/user-attachments/assets/1a49ef91-5a42-4e1f-afa0-e882b245434d
> <👷 build>[client, server]:{deployment project #8} 

- client/components/alert-defect.tsx
> <👷 build>[client, server]:{deployment project #11}

- client/app/[locale]/admin/settings/patrol-checklist/[id]/page.tsx
แก้ไขสีปุ่มเพิ่ม Item ที่แสดงไม่ถูกต้อง
> <💄 style>[client: patrol-checklist-view]:{use variant style}

- client/app/[locale]/404/page.tsx
- client/app/[locale]/admin/dashboard/heat-map/[id]/page.tsx
- client/app/[locale]/admin/employees/page.tsx
- client/app/[locale]/admin/settings/patrol-checklist/[id]/page.tsx
- client/app/[locale]/admin/settings/patrol-checklist/create/page.tsx
- client/app/[locale]/admin/settings/patrol-checklist/page.tsx
- client/app/[locale]/admin/settings/patrol-preset/[id]/page.tsx
- client/app/[locale]/admin/settings/patrol-preset/create/page.tsx
- client/app/[locale]/admin/settings/patrol-preset/error/unassinged-zone/page.tsx
- client/app/[locale]/admin/settings/patrol-preset/page.tsx
- client/app/[locale]/defect/[id]/page.tsx
- client/app/[locale]/patrol/[id]/detail/page.tsx
- client/app/[locale]/patrol/[id]/report/page.tsx
- client/app/[locale]/patrol/page.tsx
- client/app/globals.css
- client/components/gauge-graph.tsx
- client/components/header.tsx
- client/components/report-defect.tsx
- client/components/ui/alert-dialog.tsx
- client/components/ui/avatar.tsx
- client/components/user-tooltip.tsx
- client/context/patrol-context.tsx
- client/messages/en.json
- client/messages/th.json
- client/middleware.ts
- server/src/Controllers/patrol-controller.ts
- server/src/Controllers/preset-controller.ts
แก้ไข UI ให้ตรงกับ Figma
เพิ่มหน้า 404 สำหรับ id ที่หาไม่เจอ
แก้ไขหน้า HeatMap ที่มีปัญหาไม่สามารถเปิดได้
> <💄 style>[client: component]:{Update styles to match the Figma design}

- client/app/layout.tsx
> <💄 style>[client: layout]:{fix layout cannot scroll}
